import type { CommandMessages } from '../commands';

const prefix = '/agentur';

export const commands: CommandMessages = {
  help: [
    `${prefix} help — command list`, `${prefix} status — bot status in this chat`, `${prefix} doctor — connection and configuration diagnostics`, `${prefix} language — current reply language`, `${prefix} language ru|en — set reply language`, '',
    `${prefix} reply-mode — current reply policy`, `${prefix} reply-mode called — reply only to direct requests`, `${prefix} reply-mode smart — monitor the chat and intervene when useful`, `${prefix} censor-mode — current profanity policy`, `${prefix} censor-mode on — ordinary speech`, `${prefix} censor-mode off — allow profanity when appropriate`, '',
    `${prefix} identity — current agent identity`, `${prefix} identity set <description> — set agent identity`, `${prefix} identity reset — reset agent identity`, `${prefix} mood — chat mood`, `${prefix} mood reset — reset chat mood`, `${prefix} facts — saved facts`, `${prefix} decisions — saved decisions`, '',
    `${prefix} secrets — required and configured chat secrets`, `${prefix} secret set KEY VALUE — save a chat secret`, `${prefix} secret delete KEY — delete a chat secret`, '',
    `${prefix} mcp servers — connected MCP servers`, `${prefix} mcp add-remote <id> <url> — add a remote MCP server`, `${prefix} mcp set-token <id> <SECRET_KEY> — use a secret as a Bearer token`, `${prefix} mcp tools <id> — show MCP server tools`, `${prefix} mcp allow-tool <id> <tool> — allow an MCP tool`, `${prefix} mcp allow-resource <id> <uri-or-prefix*> — allow an MCP resource`, `${prefix} mcp delete <id> — delete an MCP server`, '',
    `${prefix} skills — skills and drafts`, `${prefix} skill enable <name> — enable a skill`, `${prefix} skill disable <name> — disable a skill`, `${prefix} skill delete <name> — delete a skill`, '',
    `${prefix} cron list — list cron jobs`, `${prefix} cron enable <name> — enable a cron job`, `${prefix} cron disable <name> — disable a cron job`, `${prefix} cron delete <name> — delete a cron job`,
  ].join('\n'),
  status: (replyMode, censorship, capture, tools, locale) => `Running.\nReply mode: ${replyMode}.\nProfanity mode: ${censorship}.\nContext capture: ${capture}.\nTool Calling: ${tools ? 'enabled' : 'disabled'}.\nReply language: ${locale}.`,
  noFacts: 'No facts saved yet.', noDecisions: 'No decisions saved yet.', noSkills: 'No skills yet.', noSecrets: 'There are no chat secrets and no skill requires one.', secretsHeader: 'Chat secrets:',
  secretState: (key, set, required) => `- ${key}: ${set ? '✅ Set' : '❌ Missing'}${required && !set ? ' (required)' : required ? '' : ' (not used by skills)'}`,
  secretUsage: `Use: \`${prefix} secret set KEY VALUE\``, secretSaved: (key) => `Secret ${key} saved.`, secretDeleted: (key, deleted) => deleted ? `Secret ${key} deleted.` : `Secret ${key} was not found.`,
  skillEnabled: (id, warnings = '') => `Skill enabled: ${id}${warnings}`, skillNotFound: (name) => `Skill not found: ${name}`, skillNotEnabled: (error) => `Skill was not enabled: ${error}`, skillDisabled: (name, ok) => ok ? `Skill disabled: ${name}` : `Skill was not enabled or was not found: ${name}`, skillDeleted: (name, ok) => ok ? `Skill deleted: ${name}` : `Skill not found: ${name}`,
  missingSecrets: (keys) => `\n\n⚠️ This skill requires secrets that are not set yet: ${keys.join(', ')}. Set them with:\n${keys.map((key) => `${prefix} secret set ${key} <value>`).join('\n')}`,
  noCron: 'No cron jobs yet.', cronEnabled: (id) => `Cron job enabled: ${id}`, cronNotFound: (name) => `Cron job not found: ${name}`, cronDisabled: (name, ok) => ok ? `Cron job disabled: ${name}` : `Cron job not found: ${name}`, cronDeleted: (name, ok) => ok ? `Cron job deleted: ${name}` : `Cron job not found: ${name}`,
  mood: (warmth, tension, humor) => `Mood: warmth ${warmth}, tension ${tension}, humor ${humor}.`,
  languageCurrent: (locale) => locale === 'en' ? 'Reply language: English. Change it with `/agentur language ru`.' : 'Reply language: Russian. Change it with `/agentur language en`.', languageInvalid: 'Use `/agentur language ru` or `/agentur language en`.', languageSaved: (locale) => locale === 'en' ? 'Reply language switched to English.' : 'Reply language switched to Russian.',
  replyModeCurrent: (mode) => `Current reply mode: ${mode}.\n\n\`called\` — reply only to a mention, reply, command, or skill.\n\`smart\` — monitor the chat and decide when intervention is useful.`, replyModeInvalid: `Unknown mode. Use \`${prefix} reply-mode called\` or \`${prefix} reply-mode smart\`.`, replyModeSaved: (mode) => mode === 'smart' ? 'Reply mode: smart. I will monitor the chat and intervene cautiously when useful.' : 'Reply mode: called. I will reply only to direct mentions, replies, commands, and skills.',
  censorCurrent: (mode) => `Current profanity mode: ${mode}.\n\n\`on\` — ordinary speech without profanity unless needed.\n\`off\` — profanity is allowed when appropriate.`, censorInvalid: `Unknown mode. Use \`${prefix} censor-mode on\` or \`${prefix} censor-mode off\`.`, censorMode: (enabled) => enabled ? 'enabled' : 'disabled', censorSaved: (enabled) => enabled ? 'Profanity mode: enabled. Returning to ordinary speech.' : 'Profanity mode: disabled. Profanity is allowed when appropriate.',
  identityReset: 'Identity reset for this chat.', identitySetUsage: `Send text after \`${prefix} identity set ...\` or attach a \`.txt/.md\` file with caption \`${prefix} identity set\`.`, identityTooLong: (length, max) => `Identity is too long: ${length} characters. Shorten it to ${max} characters and try again.`, identitySaved: (length) => `Identity saved for this chat (${length} characters).`, identityCurrent: (value) => value ? `Current identity:\n\n${value}` : 'No identity is set for this chat.',
  contextCapture: 'mentions, skills, and commands only',
  mcpNone: 'There are no connected MCP servers in this chat.', mcpAddFailed: (error) => `MCP server was not added: ${error}`, mcpAdded: (id, url) => `MCP server added: ${id}\nURL: ${url}\n\nIf it needs a token, save a secret and bind it as a Bearer token:\n${prefix} secret set MCP_TOKEN <value>\n${prefix} mcp set-token ${id} MCP_TOKEN\n\nInspect tools: ${prefix} mcp tools ${id}`,
  mcpNotFound: (id) => `MCP server not found: ${id}`, mcpTokenFailed: (error) => `Token secret was not saved: ${error}`, mcpTokenSaved: (key, id) => `Secret ${key} will be used as Authorization: Bearer <token> for MCP server ${id}.`, mcpDisabled: 'MCP is disabled in application settings.', mcpNoTools: (id) => `MCP server ${id} returned no tools or all tools were filtered.`, mcpToolsFailed: (id, error) => `Could not get tools from MCP server ${id}: ${error}`, mcpNoDescription: 'no description', mcpToolAllowed: (tool, id) => `Tool ${tool} allowed for MCP server ${id}.`, mcpResourceAllowed: (pattern, id) => `Resource pattern ${pattern} allowed for MCP server ${id}.`, mcpDeleted: (id, ok) => ok ? `MCP server deleted: ${id}` : `MCP server not found: ${id}`,
  mcpHelp: [`${prefix} mcp servers`, `${prefix} mcp add-remote <id> <url>`, `${prefix} mcp set-token <id> <SECRET_KEY>`, `${prefix} mcp tools <id>`, `${prefix} mcp allow-tool <id> <tool>`, `${prefix} mcp allow-resource <id> <uri-or-prefix*>`, `${prefix} mcp delete <id>`].join('\n'),
};
